networks:
  default:
    name: laravel-app

services:
  laravel:
    image: laravel-app:latest
    container_name: laravel-app
    build:
      context: .
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - OPCACHE_URL=http://localhost
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./src:/var/www
      # https://medium.com/appstract/make-your-laravel-app-fly-with-php-opcache-9948db2a5f93
      - ./conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    restart: unless-stopped
    links:
      - mysql
      - rabbitmq
      - redis

  mysql:
    image: mysql:lts
    container_name: mysql
    volumes:
      - /etc/mysql
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    volumes:
      - /data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_USER=${RABBITMQ_USER}
