services:

  laravel:
    image: laravel-app:latest
    container_name: laravel-app
    build:
      context: .
    ports:
      - "9804:9804"
    environment:
      - OPCACHE_URL=http://localhost:9804
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./src:/var/www
      # https://medium.com/appstract/make-your-laravel-app-fly-with-php-opcache-9948db2a5f93
      - ./conf/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    restart: unless-stopped
    links:
      - mysql
      - rabbitmq
      - redis

  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - /etc/mysql
      - /var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
